## Enable Full backup
backup:
  bucket_uri: ${bucket_uri}
  aws_default_region: ${s3_bucket_region}
  cron_for_full_backup: "${cron_for_full_backup}"
  mysql_database_name: "${mysql_database_name}"
  database_endpoint: "${db_endpoint}"
  database_password: "${db_password}"
  database_user: "${db_username}"


annotations:
  ${annotations}

auth:
  username: "${db_username}"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

backupjob:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
